<div id="masthead">
  <h1 id="siteName">abyle - frontend </h1>
  <div id="globalNav"> <a href="welcome.php">welcome</a>| <a href="welcome.php?link=abyle">what is abyle?</a>| <a href="welcome.php?link=abyle-frontend">what is abyle frontend?</a>| <a href="welcome.php?link=authors">authors</a>| <a href="welcome.php?link=rel_links">related links</a>| <a href="welcome.php?link=license">license</a>| <a href="http://www.abyle.org">abyle project home</a>|</div>
</div>
<h6>&nbsp;</h6>
