
  <div id="sectionLinks">
    <ul>
      <li><a href="welcome.php?link=status">firewall status</a></li>
      <li><a href="welcome.php?link=gc">global configuration </a></li>
      <li><a href="welcome.php?link=ic">interface configuration</a></li>
      <li><a href="welcome.php?link=logfile">logfile </a></li>
      <li><a href="welcome.php?link=help">help / documentation </a></li>
    </ul>
  </div>
