  <div class="relatedLinks"></div>
  
  <p class="relatedLinks">&nbsp;</p>
  <p class="relatedLinks"><strong>options</strong></p>
  <p class="relatedLinks"><a href="status.php">status</a> </p>
  <p class="relatedLinks"><a href="status.php?todo=start">start firewall</a> </p>
  <p class="relatedLinks"><a href="status.php?todo=stop">stop firewall</a> </p>
  <p class="relatedLinks"><a href="status.php?todo=restart">restart firewall</a></p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
